module.exports = {
  // ===== DAY 4 NIGHT - OPENING =====
  "*I'm back home. Lying in bed, today's memories replay like a film.*": "*Je suis rentré. Allongé dans mon lit, les souvenirs d'aujourd'hui défilent comme un film.*",

  // ===== YUNA ROUTE - Night Investigation =====
  "*10 PM. A message came from Yuna. 'School back gate. Come now.'*": "*22 heures. Un message de Yuna. 'Portail arrière de l'école. Viens maintenant.'*",
  "*My heart is pounding. The 'truth' Yuna mentioned... am I finally going to find out?*": "*Mon cœur bat la chamade. La 'vérité' dont Yuna parlait... vais-je enfin la découvrir ?*",
  "\\\"...You came. I thought you'd be late.\\\"": "\\\"...Tu es venu. Je pensais que tu serais en retard.\\\"",
  "*The school back gate. Yuna stood under a streetlight. Her expression looked more resolute than usual.*": "*Le portail arrière de l'école. Yuna se tenait sous un réverbère. Son expression semblait plus déterminée que d'habitude.*",
  "\\\"...Before we go inside, there's something you need to see first. Come this way.\\\"": "\\\"...Avant d'entrer, il y a quelque chose que tu dois voir. Suis-moi par ici.\\\"",
  "*Yuna led me to the back of the school building. A dark corner with no streetlights. When her flashlight lit up the old concrete exterior wall— I saw the crack.*": "*Yuna m'a conduit à l'arrière du bâtiment scolaire. Un coin sombre sans éclairage. Quand sa lampe torche a illuminé le vieux mur extérieur en béton — j'ai vu la fissure.*",
  "*'Crack' was too mild a word for it. Running vertically along one side of the exterior wall, a fissure as wide as a forearm stretched from top to bottom. Chunks of concrete had already fallen away in several places.*": "*'Fissure' était un mot trop faible. Le long d'un côté du mur extérieur, une crevasse large comme un avant-bras s'étendait verticalement de haut en bas. Des morceaux de béton s'étaient déjà détachés à plusieurs endroits.*",
  "\\\"This... how long has it been like this?\\\"": "\\\"Ça... depuis quand c'est comme ça ?\\\"",
  "\\\"At least three years. But the school kept delaying repairs. They've blocked students from coming over here.\\\"": "\\\"Au moins trois ans. Mais l'école n'a cessé de repousser les réparations. Ils ont interdit aux élèves de venir ici.\\\"",
  "\\\"This building had problems from the moment it was built. It wasn't constructed according to the design. Rebar spacing, concrete mix ratio... all of it was below standard.\\\"": "\\\"Ce bâtiment avait des problèmes dès sa construction. Il n'a pas été construit selon les plans. L'espacement des armatures, le dosage du béton... tout était en dessous des normes.\\\"",
  "\\\"...I like that you're honest. It's okay—I'm right here beside you.\\\"": "\\\"...J'aime ta franchise. Ça va — je suis juste là, à côté de toi.\\\"",
  "\\\"...How do you know that?\\\"": "\\\"...Comment tu sais ça ?\\\"",
  "\\\"The contractor was 'Hanjin Construction.' A company whose CEO is the brother-in-law of the foundation's chairman. Do you know where 700 million of the 1.5 billion won in construction costs went?\\\"": "\\\"L'entrepreneur était 'Hanjin Construction.' Une entreprise dont le PDG est le beau-frère du président de la fondation. Tu sais où sont passés 700 millions sur les 1,5 milliard de wons de coûts de construction ?\\\"",
  "*My chest went cold. Surely not...*": "*Mon sang s'est glacé. Ce n'est pas possible...*",
  "\\\"Into the foundation's accounts. They siphoned off the construction funds and did shoddy work. This crack is the proof. The entire school building is actually dangerous.\\\"": "\\\"Sur les comptes de la fondation. Ils ont détourné les fonds de construction et bâclé les travaux. Cette fissure en est la preuve. Tout le bâtiment scolaire est en réalité dangereux.\\\"",
  "*I looked at the crack again. It wasn't just ordinary aging. This was the trace left behind by someone's greed. The fact that hundreds of students were inside this building every day suddenly felt terrifying.*": "*J'ai regardé la fissure à nouveau. Ce n'était pas un simple vieillissement. C'était la trace laissée par l'avidité de quelqu'un. Le fait que des centaines d'élèves se trouvaient dans ce bâtiment chaque jour m'a soudain paru terrifiant.*",
  "*I couldn't believe this was real.*": "*Je n'arrivais pas à croire que c'était réel.*",
  "\\\"...The school knew about this and hid it? That's unforgivable.\\\"": "\\\"...L'école le savait et l'a caché ? C'est impardonnable.\\\"",
  "\\\"...Should we really be getting involved in this?\\\"": "\\\"...On devrait vraiment s'en mêler ?\\\"",
  "\\\"...That's how I felt at first too. But anger alone isn't enough. That's why I needed evidence. It's downstairs. Follow me.\\\"": "\\\"...C'est ce que j'ai ressenti au début aussi. Mais la colère seule ne suffit pas. C'est pour ça que j'avais besoin de preuves. C'est en bas. Suis-moi.\\\"",
  "\\\"...Being scared is natural. I felt the same way for a whole year. But now you know. Can you pretend you don't?\\\"": "\\\"...Avoir peur, c'est normal. J'ai ressenti la même chose pendant un an. Mais maintenant tu sais. Tu peux faire semblant de ne rien savoir ?\\\"",
  "*Yuna's words struck deep. I couldn't pretend not to know. I'd already seen this crack with my own eyes.*": "*Les mots de Yuna m'ont frappé en plein cœur. Je ne pouvais pas faire semblant de ne rien savoir. J'avais déjà vu cette fissure de mes propres yeux.*",
  "\\\"...I have something to show you today. Are you prepared?\\\"": "\\\"...J'ai quelque chose à te montrer aujourd'hui. Tu es prêt ?\\\"",
  "*The look in Yuna's eyes is serious.*": "*Le regard de Yuna est grave.*",
  "\\\"Of course. That's why I came.\\\"": "\\\"Bien sûr. C'est pour ça que je suis venu.\\\"",
  "\\\"...Honestly, I'm a little scared.\\\"": "\\\"...Honnêtement, j'ai un peu peur.\\\"",
  "\\\"...Good. Follow me.\\\"": "\\\"...Bien. Suis-moi.\\\"",
  "*Yuna opened the back gate lock with practiced ease. As if she'd done this many times before.*": "*Yuna a ouvert la serrure du portail arrière avec une aisance experte. Comme si elle l'avait fait de nombreuses fois.*",
  "*The empty school hallway. Only the dim emergency lights were on. The place that was so noisy during the day now felt like even a breath would echo.*": "*Le couloir vide de l'école. Seules les faibles lumières de secours étaient allumées. L'endroit si bruyant en journée semblait maintenant si silencieux qu'un souffle y résonnerait.*",
  "\\\"...The underground archives. A section the school sealed off. Everything's in here.\\\"": "\\\"...Les archives souterraines. Une section que l'école a condamnée. Tout est ici.\\\"",
  "*As we descended underground, the air turned cold. The smell of dust and old documents stung my nose.*": "*En descendant sous terre, l'air est devenu glacial. L'odeur de poussière et de vieux documents m'a piqué le nez.*",
  "\\\"This school's foundation... 'Sungjin Academy.' They claim to be an elite educational institution, but they've been operating a slush fund systematically for the past ten years.\\\"": "\\\"La fondation de cette école... 'Académie Sungjin.' Ils prétendent être une institution éducative d'élite, mais ils gèrent une caisse noire de manière systématique depuis dix ans.\\\"",
  "\\\"...A slush fund?\\\"": "\\\"...Une caisse noire ?\\\"",
  "\\\"Embezzling student welfare funds, false claims for facility repair costs, misappropriation of donations... It's all here.\\\"": "\\\"Détournement des fonds d'aide aux élèves, fausses factures de réparation, malversation des dons... Tout est là.\\\"",
  "*Yuna pulled out a worn file from the shelf. Dense numbers and stamps filled the pages. This is... a real ledger.*": "*Yuna a sorti un dossier usé de l'étagère. Des chiffres serrés et des tampons remplissaient les pages. C'est... un vrai livre de comptes.*",
  "\\\"Especially this building... the east staircase of the main hall. Records say it was renovated three years ago, but in reality, not a single penny was spent.\\\"": "\\\"Surtout ce bâtiment... l'escalier est du hall principal. Les registres indiquent qu'il a été rénové il y a trois ans, mais en réalité, pas un centime n'a été dépensé.\\\"",
  "\\\"...And on those stairs, an accident happened one year ago.\\\"": "\\\"...Et dans cet escalier, un accident s'est produit il y a un an.\\\"",
  "*Yuna's voice is trembling.*": "*La voix de Yuna tremble.*",
  "\\\"...Who got hurt?\\\"": "\\\"...Qui a été blessé ?\\\"",
  "\\\"Yuna... are you okay?\\\"": "\\\"Yuna... ça va ?\\\"",
  "\\\"...You're the first person to ask me that.\\\"": "\\\"...Tu es la première personne à me demander ça.\\\"",
  "\\\"...Lee Junho, a senior. He was the student council president at the time. He found out about the foundation's corruption and was gathering evidence.\\\"": "\\\"...Lee Junho, un élève plus âgé. Il était président du conseil des élèves à l'époque. Il avait découvert la corruption de la fondation et rassemblait des preuves.\\\"",
  "\\\"He was... a person with a strong sense of justice. Almost foolishly so. He could never look away when someone was being wronged.\\\"": "\\\"C'était... quelqu'un avec un sens aigu de la justice. Presque naïvement. Il ne pouvait jamais détourner le regard quand quelqu'un subissait une injustice.\\\"",
  "\\\"Then one day... he fell from that east staircase. The school ruled it an 'accidental fall.'\\\"": "\\\"Et puis un jour... il est tombé de cet escalier est. L'école a conclu à une 'chute accidentelle.'\\\"",
  "\\\"...An accidental fall? The person who was investigating the corruption?\\\"": "\\\"...Une chute accidentelle ? La personne qui enquêtait sur la corruption ?\\\"",
  "\\\"...The old staircase railing that was never repaired broke. If the foundation hadn't embezzled the repair funds, that accident would never have happened.\\\"": "\\\"...La vieille rampe d'escalier qui n'avait jamais été réparée s'est brisée. Si la fondation n'avait pas détourné les fonds de réparation, cet accident ne serait jamais arrivé.\\\"",
  "\\\"It was the day before he planned to take the evidence to the Board of Education. Whether it was coincidence or not... I still don't know.\\\"": "\\\"C'était la veille du jour où il comptait apporter les preuves au Rectorat. Que ce soit une coïncidence ou non... je ne sais toujours pas.\\\"",
  "\\\"He... passed away in the hospital a few days later. He never woke up.\\\"": "\\\"Il est... décédé à l'hôpital quelques jours plus tard. Il ne s'est jamais réveillé.\\\"",
  "*Yuna's hands were shaking. Her fingertips, gripping the documents, had turned white.*": "*Les mains de Yuna tremblaient. Le bout de ses doigts, agrippés aux documents, était devenu blanc.*",
  "*...*": "*...*",
  "Take Yuna's hand": "Prendre la main de Yuna",
  "\\\"...Keep talking. I'm listening.\\\"": "\\\"...Continue. Je t'écoute.\\\"",
  "\\\"...!\\\"": "\\\"... !\\\"",
  "*Yuna's hand was cold. But she didn't pull away.*": "*La main de Yuna était glacée. Mais elle ne s'est pas dégagée.*",
  "\\\"...Thank you.\\\"": "\\\"...Merci.\\\"",
  "\\\"...And one more thing. This is the most important part.\\\"": "\\\"...Et encore une chose. C'est la plus importante.\\\"",
  "\\\"The foundation's corruption started with the chairman ten years ago. But now... what's happened in the last two years is different. More calculated, more organized.\\\"": "\\\"La corruption de la fondation a commencé avec le président il y a dix ans. Mais maintenant... ce qui s'est passé ces deux dernières années est différent. Plus calculé, plus organisé.\\\"",
  "\\\"...More calculated? Who?\\\"": "\\\"...Plus calculé ? Par qui ?\\\"",
  "\\\"...Seoyeon.\\\"": "\\\"...Seoyeon.\\\"",
  "*It felt like my heart stopped.*": "*J'ai eu l'impression que mon cœur s'est arrêté.*",

  // ===== YUNA ROUTE - Seoyeon Revelation =====
  "\\\"...Seoyeon? Seoyeon from our class? What are you—\\\"": "\\\"...Seoyeon ? La Seoyeon de notre classe ? Qu'est-ce que tu—\\\"",
  "\\\"Seoyeon is the chairman's granddaughter. The chairman of this school's foundation, 'Sungjin Academy'... the granddaughter of the Sungjin Group chairman.\\\"": "\\\"Seoyeon est la petite-fille du président. Le président de la fondation de cette école, 'l'Académie Sungjin'... la petite-fille du président du Groupe Sungjin.\\\"",
  "*My mind went blank. Seoyeon... that girl who always smiled so brightly. Those curious eyes. The chairman's granddaughter?*": "*Mon esprit s'est vidé. Seoyeon... cette fille qui souriait toujours si joyeusement. Ces yeux curieux. La petite-fille du président ?*",
  "\\\"Misuse of student council funds, fraudulent scholarship applications, manipulation of school disciplinary records... everything that happened in the last two years, Seoyeon designed it herself, with the foundation backing her.\\\"": "\\\"Détournement des fonds du conseil des élèves, demandes de bourses frauduleuses, manipulation des dossiers disciplinaires... tout ce qui s'est passé ces deux dernières années, Seoyeon l'a orchestré elle-même, avec le soutien de la fondation.\\\"",
  "\\\"...I can't believe it. Seoyeon isn't that kind of person.\\\"": "\\\"...Je n'arrive pas à y croire. Seoyeon n'est pas ce genre de personne.\\\"",
  "\\\"...I thought the same thing. At first. But look at these documents.\\\"": "\\\"...J'ai pensé la même chose. Au début. Mais regarde ces documents.\\\"",
  "*Yuna handed me a stack of documents. Student council financial reports, scholarship selection lists, school disciplinary committee meeting minutes... Every document had the Seoyeon's same signature.*": "*Yuna m'a tendu une pile de documents. Rapports financiers du conseil des élèves, listes de sélection de bourses, procès-verbaux du comité disciplinaire... Chaque document portait la même signature de Seoyeon.*",
  "\\\"Seoyeon used her position as student council president to control the flow of money. On the surface, a perfect student — behind the scenes, doing exactly what the foundation told her to.\\\"": "\\\"Seoyeon a utilisé son poste de présidente du conseil des élèves pour contrôler les flux d'argent. En apparence, une élève parfaite — dans l'ombre, exécutant exactement ce que la fondation lui dictait.\\\"",
  "*The documents in my hands trembled. Seoyeon's smiling face flashed through my mind. That natural smile, those bright eyes... was all of it an act?*": "*Les documents tremblaient entre mes mains. Le visage souriant de Seoyeon m'est revenu en mémoire. Ce sourire naturel, ces yeux brillants... tout cela n'était-il qu'une comédie ?*",
  "\\\"...Whether Seoyeon is a bad person or not, I don't know. She's been inside that system since birth. But that doesn't excuse it. Because there are real people who were hurt.\\\"": "\\\"...Que Seoyeon soit une mauvaise personne ou non, je ne sais pas. Elle est dans ce système depuis sa naissance. Mais ça ne l'excuse pas. Parce qu'il y a de vraies victimes.\\\"",
  "*I couldn't accept this.*": "*Je ne pouvais pas accepter ça.*",
  "\\\"...I want to ask Seoyeon directly.\\\"": "\\\"...Je veux le demander directement à Seoyeon.\\\"",
  "\\\"...Okay. There's evidence. Let's move forward.\\\"": "\\\"...D'accord. Il y a des preuves. Allons de l'avant.\\\"",
  "\\\"...That's not possible. It's still too dangerous. The moment Seoyeon realizes, the evidence could disappear.\\\"": "\\\"...C'est impossible. C'est encore trop dangereux. Dès que Seoyeon s'en rendra compte, les preuves pourraient disparaître.\\\"",
  "*I knew she was right... but I couldn't easily accept it. Seoyeon's face kept floating before my eyes.*": "*Je savais qu'elle avait raison... mais je ne pouvais pas l'accepter facilement. Le visage de Seoyeon ne cessait d'apparaître devant mes yeux.*",
  "\\\"...Thank you. For believing me.\\\"": "\\\"...Merci. De m'avoir crue.\\\"",
  "*The cold of the basement seeped into my bones. Seoyeon. The foundation. The senior's death. The crack in the wall. Everything was connecting into one. And Yuna had been carrying all of this alone.*": "*Le froid du sous-sol me transperçait les os. Seoyeon. La fondation. La mort de l'aîné. La fissure dans le mur. Tout se connectait. Et Yuna avait porté tout cela seule.*",

  // ===== YUNA ROUTE - Resemblance & Confession =====
  "\\\"...Actually, there's one more thing I need to tell you.\\\"": "\\\"...En fait, il y a encore quelque chose que je dois te dire.\\\"",
  "\\\"When you first transferred here... I almost stopped breathing.\\\"": "\\\"Quand tu as été transféré ici... j'ai failli arrêter de respirer.\\\"",
  "\\\"...Why?\\\"": "\\\"...Pourquoi ?\\\"",
  "\\\"You... look like Junho. Your eyes, your aura. Even that feeling of never being able to stand by when something's wrong.\\\"": "\\\"Tu... ressembles à Junho. Tes yeux, ton aura. Même cette impression de ne jamais pouvoir rester les bras croisés face à l'injustice.\\\"",
  "\\\"...So at first, I was scared. Afraid the same thing would happen again. Afraid you'd be in danger too.\\\"": "\\\"...Alors au début, j'avais peur. Peur que la même chose se reproduise. Peur que tu sois en danger toi aussi.\\\"",
  "\\\"But at the same time... with you by my side, I felt like I could finish what he couldn't.\\\"": "\\\"Mais en même temps... avec toi à mes côtés, j'avais l'impression de pouvoir finir ce qu'il n'avait pas pu accomplir.\\\"",
  "*So that's why. The reason Yuna showed interest in me from the start. When she called me a 'special light'... was I just the senior's shadow?*": "*Alors c'était ça. La raison pour laquelle Yuna s'est intéressée à moi dès le début. Quand elle m'a appelé une 'lumière spéciale'... n'étais-je que l'ombre de cet aîné ?*",
  "*...What should I say?*": "*...Que devrais-je dire ?*",
  "\\\"I'm not him. I'm me. But still... I'll fight alongside you.\\\"": "\\\"Je ne suis pas lui. Je suis moi. Mais quand même... je me battrai à tes côtés.\\\"",
  "\\\"Even if I'm his stand-in, that's fine. I want to be the person you need.\\\"": "\\\"Même si je ne suis que son remplaçant, ça me va. Je veux être la personne dont tu as besoin.\\\"",
  "\\\"...So you approached me because of him? As a replacement?\\\"": "\\\"...Alors tu t'es rapprochée de moi à cause de lui ? Comme un remplaçant ?\\\"",
  "\\\"...I know. You are you. Maybe at first I was chasing the senior's shadow. But now...\\\"": "\\\"...Je sais. Tu es toi. Peut-être qu'au début je poursuivais l'ombre de cet aîné. Mais maintenant...\\\"",
  "\\\"...Now I see you. Only you.\\\"": "\\\"...Maintenant je ne vois que toi. Toi seul.\\\"",
  "\\\"Idiot... you can't just say things like that.\\\"": "\\\"Idiot... tu ne peux pas dire des choses comme ça.\\\"",
  "\\\"You're not a stand-in. You... are already more than enough, just as yourself.\\\"": "\\\"Tu n'es pas un remplaçant. Tu... es déjà plus que suffisant, tel que tu es.\\\"",
  "\\\"...\\\"": "\\\"...\\\"",
  "\\\"...I won't deny it. At first, that's how it was. But... as we spent time together, that changed. This is real.\\\"": "\\\"...Je ne le nierai pas. Au début, c'était comme ça. Mais... au fil du temps passé ensemble, ça a changé. C'est réel.\\\"",
  "\\\"...Even if you don't believe me, I'll prove it.\\\"": "\\\"...Même si tu ne me crois pas, je te le prouverai.\\\"",

  // ===== YUNA ROUTE - Evidence & Resolution =====
  "\\\"...I made copies of these documents. The originals stay here.\\\"": "\\\"...J'ai fait des copies de ces documents. Les originaux restent ici.\\\"",
  "\\\"What the senior couldn't finish... I want to see it through this time. I'm reporting it to the Press and Board of Education.\\\"": "\\\"Ce que l'aîné n'a pas pu accomplir... je veux le mener à bien cette fois. Je vais le signaler à la presse et au Rectorat.\\\"",
  "*Determination filled Yuna's eyes. This wasn't mere curiosity. She'd been uncovering the truth alone for an entire year.*": "*La détermination emplissait les yeux de Yuna. Ce n'était pas de la simple curiosité. Elle avait enquêté seule sur la vérité pendant une année entière.*",
  "\\\"...But it could be dangerous. The foundation won't sit still.\\\"": "\\\"...Mais ça pourrait être dangereux. La fondation ne va pas rester les bras croisés.\\\"",
  "\\\"...Let's do this together. Don't carry it all alone.\\\"": "\\\"...Faisons-le ensemble. Ne porte pas tout ça toute seule.\\\"",
  "Yuna gently takes your hand, her touch no longer cold, but warm and seeking comfort.": "Yuna prend doucement ta main ; son toucher n'est plus froid, mais chaud, en quête de réconfort.",
  "*We slipped out of the school. The cold night breeze blew, but it felt less cold with Yuna beside me.*": "*Nous nous sommes faufilés hors de l'école. La brise froide de la nuit soufflait, mais elle semblait moins glaciale avec Yuna à mes côtés.*",
  "\\\"...Thank you for today. It's the first time I've told anyone what I've been carrying alone.\\\"": "\\\"...Merci pour aujourd'hui. C'est la première fois que je confie à quelqu'un ce que je portais seule.\\\"",
  "\\\"...It was a heavy day, wasn't it?\\\"": "\\\"...C'était une journée lourde, non ?\\\"",
  "*Under the night sky, Yuna smiles awkwardly.*": "*Sous le ciel nocturne, Yuna sourit maladroitement.*",
  "\\\"No. Because I got to know you better.\\\"": "\\\"Non. Parce que j'ai appris à mieux te connaître.\\\"",
  "\\\"Next time, let's go on a real date. Somewhere like a café.\\\"": "\\\"La prochaine fois, allons à un vrai rendez-vous. Dans un café, par exemple.\\\"",
  "\\\"...That's not fair, saying something like that.\\\"": "\\\"...C'est pas juste de dire un truc pareil.\\\"",
  "\\\"...A café. I'd like that. Can I pick the place this time?\\\"": "\\\"...Un café. Ça me plairait. Je peux choisir l'endroit cette fois ?\\\"",

  // ===== YUNA ROUTE - Yandere Ending =====
  "*Yuna stopped as she was about to turn around. And she gripped my collar tightly.*": "*Yuna s'est arrêtée alors qu'elle allait se retourner. Et elle a agrippé fermement mon col.*",
  "I won't let you die like he did. To protect you... I'd rather break you and tie you to my side.": "Je ne te laisserai pas mourir comme lui. Pour te protéger... je préfère te briser et t'enchaîner à moi.",
  "You're mine. You can't go anywhere.": "Tu es à moi. Tu ne peux aller nulle part.",
  "*I returned home. Yuna's chilling gaze and tight grip won't leave my mind.*": "*Je suis rentré chez moi. Le regard glaçant de Yuna et sa poigne serrée ne quittent pas mon esprit.*",
  "*I had a feeling that what she meant by 'protecting' might be different from what I thought.*": "*J'avais le pressentiment que ce qu'elle entendait par 'protéger' était différent de ce que je pensais.*",

  // ===== SEOYEON ROUTE - Night Call =====
  "*9 PM. A call from Seoyeon.*": "*21 heures. Un appel de Seoyeon.*",
  "\\\"...Hey, it's me. If you're not busy... could you come out for a bit?\\\"": "\\\"...Salut, c'est moi. Si tu n'es pas occupé... tu pourrais sortir un moment ?\\\"",
  "*Seoyeon's voice sounds different from usual. No warmth, and it seems like she's trembling.*": "*La voix de Seoyeon est différente de d'habitude. Aucune chaleur, et elle semble trembler.*",
  "\\\"...You know the park near my house, right? I'll wait there.\\\"": "\\\"...Tu connais le parc près de chez moi, non ? Je t'attends là-bas.\\\"",
  "*I arrived at the park. Seoyeon was sitting alone on a bench. Instead of her usual neat uniform, she wore casual clothes.*": "*Je suis arrivé au parc. Seoyeon était assise seule sur un banc. Au lieu de son uniforme soigné habituel, elle portait des vêtements décontractés.*",
  "\\\"...You came. Sorry for calling you out so suddenly.\\\"": "\\\"...Tu es venu. Pardon de t'avoir appelé si soudainement.\\\"",
  "*Seoyeon's eyes are red. ...Was she crying?*": "*Les yeux de Seoyeon sont rouges. ...Elle pleurait ?*",
  "\\\"What happened? Are you okay?\\\"": "\\\"Qu'est-ce qui s'est passé ? Ça va ?\\\"",
  "Sit next to her without saying anything": "S'asseoir à côté d'elle sans rien dire",
  "\\\"...If I said I was fine, that would be a lie.\\\"": "\\\"...Si je disais que ça va, ce serait un mensonge.\\\"",
  "\\\"...Thank you. Just sitting next to me... that's the best thing.\\\"": "\\\"...Merci. Juste être assis à côté de moi... c'est ce qu'il y a de mieux.\\\"",

  // ===== SEOYEON ROUTE - Family Drama =====
  "\\\"...Mom called today. She and Dad had another fight.\\\"": "\\\"...Maman a appelé aujourd'hui. Elle et papa se sont encore disputés.\\\"",
  "\\\"Our house... looks perfect from the outside, right? Big house, nice car, student council president daughter.\\\"": "\\\"Notre maison... semble parfaite de l'extérieur, non ? Grande maison, belle voiture, fille présidente du conseil des élèves.\\\"",
  "\\\"But actually... Mom and Dad haven't lived under the same roof for a year now. They just haven't filed for divorce yet.\\\"": "\\\"Mais en réalité... maman et papa ne vivent plus sous le même toit depuis un an. Ils n'ont juste pas encore demandé le divorce.\\\"",
  "\\\"Mom said, 'At least you need to be perfect for this family to hold together.' So... student council, grades, I couldn't let go of any of it.\\\"": "\\\"Maman a dit : 'Au moins, toi, tu dois être parfaite pour que cette famille tienne.' Alors... le conseil des élèves, les notes, je ne pouvais rien lâcher.\\\"",
  "\\\"I had to smile for everyone. 'Seoyeon is always so bright,' 'Seoyeon is good at everything.' Those words... started to feel like a prison.\\\"": "\\\"Je devais sourire pour tout le monde. 'Seoyeon est toujours si radieuse,' 'Seoyeon est bonne en tout.' Ces mots... ont commencé à ressembler à une prison.\\\"",
  "\\\"I wasn't smiling—I was 'performing' a smile. Every single day.\\\"": "\\\"Je ne souriais pas — je 'jouais' le sourire. Chaque jour.\\\"",
  "*Tears spilled from Seoyeon's eyes. Glistening under the streetlight. It was the first time I'd ever seen her cry.*": "*Des larmes ont coulé des yeux de Seoyeon. Scintillant sous le réverbère. C'était la première fois que je la voyais pleurer.*",
  "*Seoyeon is crying. I've never seen this side of her.*": "*Seoyeon pleure. Je n'avais jamais vu ce côté d'elle.*",
  "Hug Seoyeon": "Serrer Seoyeon dans ses bras",
  "Offer a pinky promise": "Lui proposer une promesse du petit doigt",
  "\\\"...... !\\\"": "\\\"...... !\\\"",
  "*Seoyeon buried her face in my chest. Her small shoulders were trembling.*": "*Seoyeon a enfoui son visage contre ma poitrine. Ses petites épaules tremblaient.*",
  "\\\"...It's been so long since I cried like this. Crying in front of someone... this is the first time.\\\"": "\\\"...Ça faisait tellement longtemps que je n'avais pas pleuré comme ça. Pleurer devant quelqu'un... c'est la première fois.\\\"",
  "\\\"I promise. Whenever you want to cry, you can cry with me.\\\"": "\\\"Je te le promets. Quand tu voudras pleurer, tu pourras pleurer avec moi.\\\"",
  "\\\"...A pinky promise?\\\"": "\\\"...Une promesse du petit doigt ?\\\"",
  "*Seoyeon locked her trembling pinky with mine. And then the tears she'd been holding back poured out.*": "*Seoyeon a noué son petit doigt tremblant au mien. Et les larmes qu'elle retenait se sont déversées.*",
  "\\\"...You fool, why are you... so kind to me...\\\"": "\\\"...Idiot, pourquoi tu es... si gentil avec moi...\\\"",
  "\\\"...Even during our date today, I was scared. Am I allowed to be this happy? Will this happiness crumble too?\\\"": "\\\"...Même pendant notre rendez-vous aujourd'hui, j'avais peur. Ai-je le droit d'être si heureuse ? Est-ce que ce bonheur va s'effondrer aussi ?\\\"",
  "\\\"Are you... okay with a me that's not perfect?\\\"": "\\\"Tu... acceptes une version de moi qui n'est pas parfaite ?\\\"",
  "*Seoyeon is looking up at me with trembling eyes.*": "*Seoyeon me regarde avec des yeux tremblants.*",
  "\\\"I like the Seoyeon right now more than the perfect one.\\\"": "\\\"J'aime la Seoyeon d'en ce moment plus que la parfaite.\\\"",
  "\\\"Not the class president Seoyeon—just Seoyeon is my girlfriend.\\\"": "\\\"Pas la Seoyeon présidente du conseil — juste Seoyeon est ma petite amie.\\\"",
  "\\\"Honestly, I always thought you were perfect. But... thank you for showing me this side too.\\\"": "\\\"Honnêtement, je t'ai toujours trouvée parfaite. Mais... merci de me montrer aussi ce côté de toi.\\\"",
  "\\\"...Really?\\\"": "\\\"...Vraiment ?\\\"",
  "\\\"...I'll never forget those words. If I do... we made a pinky promise, after all.\\\"": "\\\"...Je n'oublierai jamais ces mots. Si jamais... on a fait une promesse du petit doigt, après tout.\\\"",
  "\\\"G-girlfriend......\\\"": "\\\"P-petite amie......\\\"",
  "\\\"...Ah, my heart is pounding so hard I might die. You can't just say things like that...\\\"": "\\\"...Ah, mon cœur bat si fort que je pourrais mourir. Tu ne peux pas dire des choses comme ça...\\\"",
  "\\\"...Thank you. Do you mean it?\\\"": "\\\"...Merci. Tu le penses vraiment ?\\\"",
  "\\\"From now on... I won't act in front of you. I promise.\\\"": "\\\"Désormais... je ne ferai plus semblant devant toi. Promis.\\\"",
  "\\\"...You know what? I've made up my mind.\\\"": "\\\"...Tu sais quoi ? Je me suis décidée.\\\"",
  "\\\"I'm going to tell Mom. That I want to be myself before being 'the perfect daughter.'\\\"": "\\\"Je vais le dire à maman. Que je veux être moi-même avant d'être 'la fille parfaite.'\\\"",

  // ===== SEOYEON ROUTE - Yandere Ending =====
  "Since you've seen me at my lowest like this... you can never leave me now.": "Puisque tu m'as vue au plus bas comme ça... tu ne pourras plus jamais me quitter.",
  "......Seoyeon?": "......Seoyeon ?",
  "If you smile at another girl... I don't know what I'll do then. Got it?": "Si tu souris à une autre fille... je ne sais pas ce que je ferai. Compris ?",
  "*We left the park and walked together to my house. Seoyeon hugged my arm tightly and wouldn't let go.*": "*Nous avons quitté le parc et marché ensemble jusqu'à chez moi. Seoyeon serrait mon bras et ne voulait pas lâcher.*",
  "...I showed you an ugly side of me today, but you didn't run away. I'm glad.": "...Je t'ai montré un côté laid de moi aujourd'hui, mais tu n'as pas fui. Je suis contente.",
  "\\\"Run away? I actually like you more now.\\\"": "\\\"Fuir ? En fait, je t'aime encore plus maintenant.\\\"",
  "......Never forget those words. You're mine now.": "......N'oublie jamais ces mots. Tu es à moi maintenant.",
  "*As Seoyeon turned to leave, she said in a small voice.*": "*Alors que Seoyeon se retournait pour partir, elle a dit d'une petite voix.*",
  "*As Seoyeon turned around, she gave a chilling but sweet smile.*": "*En se retournant, Seoyeon a affiché un sourire glaçant mais doux.*",
  "*Back home. Seoyeon's tears keep coming back to me. The real face behind the perfect student council president... I want to share that heavy burden.*": "*De retour chez moi. Les larmes de Seoyeon me reviennent sans cesse. Le vrai visage derrière la présidente parfaite du conseil des élèves... je veux partager ce lourd fardeau.*",
  "*Tomorrow... I want her smile to come from the heart, not from acting.*": "*Demain... je veux que son sourire vienne du cœur, pas d'un rôle qu'elle joue.*",

  // ===== DAIN ROUTE - Night Gym =====
  "*9:30 PM. A message from Dain. 'Hey, you free rn?? lol Can you come to school??'*": "*21h30. Un message de Dain. 'Hey, t'es libre là ?? mdr Tu peux venir à l'école ??'*",
  "*Another message right away. 'Nvm just come lol! Gym back door is open!'*": "*Un autre message aussitôt. 'Laisse tomber viens c'est tout mdr ! La porte arrière du gymnase est ouverte !'*",
  "*Dain at the school gym at this hour? Something feels off... Let's go check.*": "*Dain au gymnase de l'école à cette heure ? Quelque chose cloche... Allons voir.*",
  "*I entered the gym. In the darkness lit only by emergency lights, Dain was alone, bumping a volleyball.*": "*Je suis entré dans le gymnase. Dans l'obscurité éclairée uniquement par les lumières de secours, Dain était seule, faisant rebondir un ballon de volley.*",
  "\\\"Oh! You actually came?! Hehe, that's my boyfriend!\\\"": "\\\"Oh ! T'es vraiment venu ?! Héhé, c'est bien mon copain !\\\"",
  "*But... something's off. Dain seems to be smiling harder than usual.*": "*Mais... quelque chose ne va pas. Dain semble sourire plus fort que d'habitude.*",
  "\\\"Toss for me! Just once! I'll show you my spike!!\\\"": "\\\"Fais-moi une passe ! Juste une fois ! Je vais te montrer mon smash !!\\\"",
  "*I tossed the ball to Dain. She jumped high and slammed the spike down.*": "*J'ai lancé le ballon à Dain. Elle a sauté haut et a claqué le smash.*",
  "*The moment she landed—Dain grabbed her right knee and crumpled to the floor.*": "*Au moment de l'atterrissage — Dain a saisi son genou droit et s'est effondrée au sol.*",
  "\\\"...... !!\\\"": "\\\"...... !!\\\"",
  "\\\"Dain!!\\\"": "\\\"Dain !!\\\"",
  "\\\"Ow ow!! I'm fine!! Just tweaked it a little haha, no biggie...\\\"": "\\\"Aïe aïe !! Ça va !! J'ai juste un peu forcé haha, c'est rien...\\\"",
  "*Dain is smiling, but her hand gripping her knee has gone white.*": "*Dain sourit, mais sa main qui agrippe son genou est devenue blanche.*",
  "\\\"Don't lie. Let me see.\\\"": "\\\"Ne mens pas. Laisse-moi voir.\\\"",
  "\\\"Dain. You're not okay.\\\"": "\\\"Dain. Tu ne vas pas bien.\\\"",
  "*When I tried to look at Dain's knee, she flinched and pulled away.*": "*Quand j'ai essayé de regarder le genou de Dain, elle a sursauté et s'est reculée.*",
  "\\\"......\\\"": "\\\"......\\\"",
  "\\\"...Fine. I was trying to hide it.\\\"": "\\\"...Bon. J'essayais de le cacher.\\\"",
  "*Dain rolled up her knee brace. Her knee was badly swollen.*": "*Dain a remonté sa genouillère. Son genou était terriblement enflé.*",
  "\\\"...Torn ACL. I injured it last year. Had surgery but... it never fully healed.\\\"": "\\\"...Rupture des ligaments croisés. Je me suis blessée l'an dernier. J'ai été opérée mais... ça n'a jamais complètement guéri.\\\"",
  "\\\"...Last year?\\\"": "\\\"...L'an dernier ?\\\"",
  "\\\"The doctor said, 'Daily life is fine, but playing like before is too much.'\\\"": "\\\"Le médecin a dit : 'La vie quotidienne, pas de souci, mais rejouer comme avant, c'est trop.'\\\"",
  "\\\"Athletic scholarship, going pro... All gone. Just like that.\\\"": "\\\"Bourse sportive, devenir pro... Tout envolé. Comme ça.\\\"",
  "*...For Dain, who lived for volleyball, that must have been a death sentence.*": "*...Pour Dain, qui vivait pour le volley, ça a dû être une condamnation à mort.*",
  "\\\"...You know how I always smile? Nobody knows it's an act.\\\"": "\\\"...Tu sais que je souris toujours ? Personne ne sait que c'est du cinéma.\\\"",
  "\\\"'Dain is always so energetic!' Every time I hear that... I laugh for real. But inside, my knee burns every single day.\\\"": "\\\"'Dain est toujours pleine d'énergie !' Chaque fois que j'entends ça... je ris pour de vrai. Mais à l'intérieur, mon genou me brûle chaque jour.\\\"",
  "\\\"Even on our date today, when we were running around... it actually hurt. But I didn't want to show it.\\\"": "\\\"Même pendant notre rendez-vous aujourd'hui, quand on courait partout... ça faisait vraiment mal. Mais je ne voulais pas le montrer.\\\"",
  "\\\"I know I need to let go. But... I just wanted to jump one more time. On this court.\\\"": "\\\"Je sais que je dois tourner la page. Mais... je voulais juste sauter une dernière fois. Sur ce terrain.\\\"",
  "*Dain hugged the volleyball tight and lowered her head. Her shoulders were shaking. The girl who was always bright and cheerful... was crying.*": "*Dain a serré le ballon de volley contre elle et a baissé la tête. Ses épaules tremblaient. La fille toujours joyeuse et pleine d'entrain... pleurait.*",
  "*...What do I say?*": "*...Qu'est-ce que je dis ?*",
  "\\\"Your dream isn't just volleyball. Let's find a new dream together.\\\"": "\\\"Ton rêve, ce n'est pas que le volley. Trouvons un nouveau rêve ensemble.\\\"",
  "\\\"You can cry. You don't have to pretend to be okay. Not with me.\\\"": "\\\"Tu peux pleurer. Tu n'as pas besoin de faire semblant d'aller bien. Pas avec moi.\\\"",
  "\\\"...Want me to toss one more? One last time.\\\"": "\\\"...Tu veux que je fasse encore une passe ? Une dernière fois.\\\"",

  // ===== DAIN ROUTE - New Dream =====
  "\\\"...A new dream?\\\"": "\\\"...Un nouveau rêve ?\\\"",
  "\\\"...I've thought about it. Coaching, training... I do love teaching people.\\\"": "\\\"...J'y ai réfléchi. Entraîner, former... j'adore enseigner aux gens.\\\"",
  "\\\"You'd be the most passionate coach in the world.\\\"": "\\\"Tu serais l'entraîneuse la plus passionnée du monde.\\\"",
  "\\\"...Dummy, if you say things like that I'll cry again...\\\"": "\\\"...Idiot, si tu dis des trucs comme ça je vais encore pleurer...\\\"",
  "\\\"...You dummy... if you say that... I'll actually cry...!!\\\"": "\\\"...Espèce d'idiot... si tu dis ça... je vais vraiment pleurer... !!\\\"",
  "*Dain buried her face in my chest and started sobbing. Her cries echoed through the empty gym.*": "*Dain a enfoui son visage contre ma poitrine et s'est mise à sangloter. Ses pleurs résonnaient dans le gymnase vide.*",
  "\\\"...I couldn't tell anyone... every day, alone... I was so scared...\\\"": "\\\"...Je ne pouvais le dire à personne... chaque jour, toute seule... j'avais tellement peur...\\\"",
  "\\\"...One last time?\\\"": "\\\"...Une dernière fois ?\\\"",
  "\\\"Not 'last'—it's 'the last one before a new beginning.'\\\"": "\\\"Pas 'dernière' — c'est 'la dernière avant un nouveau départ.'\\\"",
  "*I tossed the ball. Dain gritted her teeth and jumped, slamming down the best spike I'd ever seen. She grabbed her knee on landing... but she was smiling.*": "*J'ai lancé le ballon. Dain a serré les dents et sauté, claquant le plus beau smash que j'aie jamais vu. Elle a attrapé son genou à l'atterrissage... mais elle souriait.*",
  "\\\"...Haha. It hurts. But... it felt amazing.\\\"": "\\\"...Haha. Ça fait mal. Mais... c'était incroyable.\\\"",
  "\\\"...Thank you. I think I can really let go now.\\\"": "\\\"...Merci. Je crois que je peux vraiment tourner la page maintenant.\\\"",
  "\\\"...Hey.\\\"": "\\\"...Hé.\\\"",
  "\\\"I've decided. I'm going to talk to my doctor properly and focus on rehabilitation.\\\"": "\\\"J'ai décidé. Je vais parler sérieusement à mon médecin et me concentrer sur la rééducation.\\\"",

  // ===== DAIN ROUTE - Yandere Ending =====
  "If I can never play volleyball again... you have to take responsibility for my whole life. Got it?": "Si je ne peux plus jamais jouer au volley... tu devras prendre la responsabilité de toute ma vie. Compris ?",
  "......Huh?": "......Hein ?",
  "I'm not joking. You're mine now, so don't even think about running away. Even if my legs break, I'll chase after you.": "Je ne plaisante pas. Tu es à moi maintenant, alors n'essaie même pas de fuir. Même si mes jambes se brisent, je te poursuivrai.",
  "*We left the gym. Dain linked her arm tightly with mine, putting strength into it as if she would never let go.*": "*Nous avons quitté le gymnase. Dain a enlacé mon bras fermement, y mettant toute sa force comme si elle ne le lâcherait jamais.*",
  "...Since you've seen all my weaknesses today, you can't escape from me now. Just set tosses by my side for the rest of your life.": "...Puisque tu as vu toutes mes faiblesses aujourd'hui, tu ne peux plus m'échapper. Contente-toi de me faire des passes pour le reste de ta vie.",
  "\\\"I liked that side of you too.\\\"": "\\\"J'ai aimé ce côté de toi aussi.\\\"",
  "\\\"...Huh? Who says 'I liked it' about their crying girlfriend? Weirdo.\\\"": "\\\"...Hein ? Qui dit 'j'ai aimé ça' en parlant de sa copine en pleurs ? T'es bizarre.\\\"",
  "\\\"...But thanks. Really. Without you, I would've kept carrying this alone forever.\\\"": "\\\"...Mais merci. Vraiment. Sans toi, j'aurais continué à porter ça toute seule pour toujours.\\\"",
  "\\\"...Starting tomorrow, I'll smile for real. Not fake—for real.\\\"": "\\\"...À partir de demain, je sourirai pour de vrai. Pas du faux — pour de vrai.\\\"",
  "*Back home. Dain's tears from the gym keep flashing before my eyes. The pain she hid behind her constant brightness... it weighs heavy on my heart.*": "*De retour chez moi. Les larmes de Dain au gymnase me reviennent sans cesse. La douleur qu'elle cachait derrière sa gaieté constante... ça me pèse sur le cœur.*",
  "*Tomorrow... I want it to be a day where Dain can smile from the heart. I'll be right there beside her.*": "*Demain... je veux que ce soit un jour où Dain pourra sourire du fond du cœur. Je serai juste là, à ses côtés.*",

  // ===== TEACHER ROUTE - Night Café =====
  "*9 PM. A call from the teacher.*": "*21 heures. Un appel de la professeure.*",
  "\\\"...Hello? It's me. Are you... free right now?\\\"": "\\\"...Allô ? C'est moi. Tu es... libre en ce moment ?\\\"",
  "*Her voice sounds different from usual. Not the confident voice from the classroom... it sounds like she's about to break.*": "*Sa voix est différente de d'habitude. Pas la voix assurée de la salle de classe... on dirait qu'elle est sur le point de craquer.*",
  "\\\"...There's a café near the school. Can we meet there?\\\"": "\\\"...Il y a un café près de l'école. On peut se retrouver là-bas ?\\\"",
  "*I arrived at the café. She was sitting in a corner booth. Instead of her usual neat outfit, she was in casual clothes.*": "*Je suis arrivé au café. Elle était assise dans un coin isolé. Au lieu de sa tenue soignée habituelle, elle portait des vêtements décontractés.*",
  "\\\"...Thanks for coming. Sorry for calling you out so suddenly.\\\"": "\\\"...Merci d'être venu. Pardon de t'avoir appelé si soudainement.\\\"",
  "*Her eyes are red. ...Was she crying?*": "*Ses yeux sont rouges. ...Elle pleurait ?*",
  "\\\"Did something happen?\\\"": "\\\"Il s'est passé quelque chose ?\\\"",
  "Offer her coffee and wait quietly": "Lui offrir un café et attendre calmement",
  "\\\"...It's not so much that something happened. I just... thought a lot today.\\\"": "\\\"...Ce n'est pas tant qu'il s'est passé quelque chose. J'ai juste... beaucoup réfléchi aujourd'hui.\\\"",
  "\\\"...Thank you. Just sitting next to me without saying anything... I really like that about you.\\\"": "\\\"...Merci. Juste être assis à côté de moi sans rien dire... j'aime vraiment ça chez toi.\\\"",
  "\\\"...At the faculty meeting yesterday, the vice principal said, 'Be careful about getting too personally close to students.'\\\"": "\\\"...À la réunion des professeurs hier, le proviseur adjoint a dit : 'Faites attention à ne pas devenir trop proche personnellement des élèves.'\\\"",
  "\\\"Maybe it wasn't about us directly. But... my heart nearly stopped.\\\"": "\\\"Ce n'était peut-être pas à propos de nous directement. Mais... mon cœur a failli s'arrêter.\\\"",
  "\\\"I'm... a teacher. Your homeroom teacher. I know this isn't right.\\\"": "\\\"Je suis... une professeure. Ta professeure principale. Je sais que ce n'est pas bien.\\\"",
  "\\\"But on the way home, I kept thinking about you. 'What is he doing right now?' 'Did he eat?'...\\\"": "\\\"Mais sur le chemin du retour, je n'arrêtais pas de penser à toi. 'Qu'est-ce qu'il fait en ce moment ?' 'Est-ce qu'il a mangé ?'...\\\"",
  "\\\"Am I not qualified to be a teacher? Or... is it because these feelings are real that I feel this way?\\\"": "\\\"Ne suis-je pas faite pour être enseignante ? Ou... est-ce parce que ces sentiments sont réels que je me sens ainsi ?\\\"",
  "*She gripped her coffee cup tightly and lowered her head. Her shoulders were trembling ever so slightly.*": "*Elle a serré sa tasse de café et baissé la tête. Ses épaules tremblaient imperceptiblement.*",
  "\\\"...Ha, sorry. A teacher shouldn't be like this in front of a student.\\\"": "\\\"...Ha, pardon. Une professeure ne devrait pas être comme ça devant un élève.\\\"",
  "*There are tears glistening at the corner of her eyes.*": "*Des larmes brillent au coin de ses yeux.*",
  "Hold her hand": "Lui prendre la main",
  "\\\"Right now, you're not my teacher—you're a woman I care about\\\"": "\\\"En ce moment, tu n'es pas ma prof — tu es une femme à qui je tiens\\\"",
  "\\\"......!\\\"": "\\\"...... !\\\"",
  "*I reached under the table and held her hand. Her cold fingers slowly grew warm.*": "*J'ai glissé ma main sous la table et pris la sienne. Ses doigts froids se sont lentement réchauffés.*",
  "\\\"...We shouldn't do this here. Someone might see.\\\"": "\\\"...On ne devrait pas faire ça ici. Quelqu'un pourrait voir.\\\"",
  "\\\"...But I don't want to let go.\\\"": "\\\"...Mais je ne veux pas lâcher.\\\"",
  "\\\"...What?\\\"": "\\\"...Quoi ?\\\"",
  "\\\"Before you're a teacher, you're a person. It's okay to cry when you want to cry.\\\"": "\\\"Avant d'être professeure, tu es une personne. C'est normal de pleurer quand tu en as envie.\\\"",
  "\\\"...You, honestly.\\\"": "\\\"...Toi, franchement.\\\"",
  "\\\"...If you say things like that, I'll really start crying, you dummy.\\\"": "\\\"...Si tu dis des choses comme ça, je vais vraiment me mettre à pleurer, idiot.\\\"",

  // ===== TEACHER ROUTE - Confession =====
  "\\\"...You know, when I first became a teacher, I promised myself I'd never catch feelings for a student.\\\"": "\\\"...Tu sais, quand je suis devenue professeure, je me suis promis de ne jamais tomber amoureuse d'un élève.\\\"",
  "\\\"But then you came along... and broke that promise before I even noticed.\\\"": "\\\"Mais tu es arrivé... et tu as brisé cette promesse avant même que je m'en rende compte.\\\"",
  "\\\"When I scolded you for being late, you just smiled and said, 'You look tired today, are you okay?' instead of making excuses.\\\"": "\\\"Quand je t'ai grondé pour ton retard, tu as juste souri et dit : 'Vous avez l'air fatiguée aujourd'hui, ça va ?' au lieu de te justifier.\\\"",
  "\\\"That's when... I started noticing you.\\\"": "\\\"C'est là que... j'ai commencé à te remarquer.\\\"",
  "*She's speaking her heart with a trembling voice.*": "*Elle ouvre son cœur d'une voix tremblante.*",
  "\\\"After I graduate, I'll stand proudly by your side\\\"": "\\\"Après mon diplôme, je me tiendrai fièrement à tes côtés\\\"",
  "\\\"This moment right now is precious. That's enough for me\\\"": "\\\"Cet instant présent est précieux. Ça me suffit\\\"",
  "\\\"If it's too hard for you, we can stop\\\"": "\\\"Si c'est trop dur pour toi, on peut arrêter\\\"",
  "\\\"...After you graduate?\\\"": "\\\"...Après ton diplôme ?\\\"",
  "\\\"...Will you wait until then?\\\"": "\\\"...Tu attendras jusque-là ?\\\"",
  "\\\"I'm not waiting—I'm going to become someone even better by then.\\\"": "\\\"Je n'attends pas — je vais devenir quelqu'un d'encore mieux d'ici là.\\\"",
  "\\\"...God, seriously. You're way more mature than I am.\\\"": "\\\"...Mon Dieu, sérieusement. Tu es bien plus mature que moi.\\\"",
  "\\\"...This moment right now?\\\"": "\\\"...Cet instant présent ?\\\"",
  "\\\"We can worry about tomorrow when it comes. Right now, I just want to be here with you.\\\"": "\\\"On s'inquiétera de demain quand il viendra. Pour l'instant, je veux juste être ici avec toi.\\\"",
  "\\\"...You're right. Right now... this time together is what matters.\\\"": "\\\"...Tu as raison. Pour l'instant... ce temps ensemble est ce qui compte.\\\"",
  "\\\"...Stop?\\\"": "\\\"...Arrêter ?\\\"",
  "\\\"...You dummy. I'm not struggling because I want to stop.\\\"": "\\\"...Idiot. Ce n'est pas parce que je veux arrêter que j'ai du mal.\\\"",
  "\\\"It's because my feelings are real... that's what scares me.\\\"": "\\\"C'est parce que mes sentiments sont réels... que ça me fait peur.\\\"",
  "\\\"...You know what?\\\"": "\\\"...Tu sais quoi ?\\\"",

  // ===== TEACHER ROUTE - Yandere Ending =====
  "I've made up my mind. I don't care if I lose my position as a teacher.": "J'ai pris ma décision. Peu importe si je perds mon poste d'enseignante.",
  "If we get caught... I'll lock you in my room where no one can see you. Then only I can see you forever, right?": "Si on se fait prendre... je t'enfermerai dans ma chambre où personne ne pourra te voir. Comme ça, il n'y aura que moi pour te voir, pour toujours, non ?",
  "......Teacher?": "......Professeure ?",
  "I'm not joking. You're my accomplice now. You can never get out.": "Je ne plaisante pas. Tu es mon complice maintenant. Tu ne pourras jamais t'en sortir.",
  "*We left the cafe. We walked side by side on the night street. The teacher intertwined her fingers with mine and wouldn't let go.*": "*Nous avons quitté le café. Nous avons marché côte à côte dans la rue nocturne. La professeure a entrelacé ses doigts aux miens et n'a pas lâché.*",
  "...I'll pretend to be a strict teacher again at school. We can't let the other kids notice.": "...Je ferai semblant d'être une prof stricte à l'école. On ne peut pas laisser les autres élèves s'en apercevoir.",
  "A secret romance.": "Une romance secrète.",
  "Yeah. So... don't get too close to other girls at school.": "Oui. Alors... ne te rapproche pas trop des autres filles à l'école.",
  "You never know how I might torment you using my authority as a teacher. Got it?": "Tu ne sais pas comment je pourrais te tourmenter en utilisant mon autorité de professeure. Compris ?",
  "...See you tomorrow. My accomplice.": "...À demain. Mon complice.",
  "*Back home. The image of her at the café keeps coming back to me. The always confident, perfect teacher... showing her tears and vulnerability as just a woman.*": "*De retour chez moi. Son image au café me revient sans cesse. La professeure toujours sûre d'elle, parfaite... montrant ses larmes et sa vulnérabilité en tant que simple femme.*",
  "*This secret is daunting... but it's precious. I'll never take her feelings lightly.*": "*Ce secret est redoutable... mais il est précieux. Je ne prendrai jamais ses sentiments à la légère.*",

  // ===== NURSE ROUTE - Night Visit =====
  "*10 PM. A message from the nurse. 'Still up? Can you come out for a bit if you have time?'*": "*22 heures. Un message de l'infirmière. 'Encore debout ? Tu peux sortir un peu si tu as le temps ?'*",
  "*...Her usual playful message, but why this late? Something feels off.*": "*...Son message joueur habituel, mais pourquoi si tard ? Quelque chose ne va pas.*",
  "*I replied right away. 'Where should I go?'*": "*J'ai répondu tout de suite. 'Où est-ce que je dois aller ?'*",
  "*'The nurse's office at school. I'll leave the back door open.' ...The nurse's office?*": "*'L'infirmerie de l'école. Je laisserai la porte de derrière ouverte.' ...L'infirmerie ?*",
  "*I arrived at the school. When I opened the nurse's office door, the room was dark with only a small lamp on. She was there.*": "*Je suis arrivé à l'école. Quand j'ai ouvert la porte de l'infirmerie, la pièce était sombre, éclairée seulement par une petite lampe. Elle était là.*",
  "\\\"Wow, you actually came. Even though I called you out this late?\\\"": "\\\"Waouh, tu es vraiment venu. Même si je t'ai fait venir si tard ?\\\"",
  "*She's smiling as usual, but... there are dark circles under her eyes. And several empty coffee cans on the desk.*": "*Elle sourit comme d'habitude, mais... il y a des cernes sous ses yeux. Et plusieurs canettes de café vides sur le bureau.*",
  "\\\"You look really tired\\\"": "\\\"Tu as l'air vraiment fatiguée\\\"",
  "\\\"What's the real reason you called me here?\\\"": "\\\"C'est quoi la vraie raison pour laquelle tu m'as fait venir ?\\\"",
  "\\\"Think so? It's been a hectic week. I'm fine though, really.\\\"": "\\\"Tu trouves ? C'était une semaine mouvementée. Mais ça va, vraiment.\\\"",
  "\\\"...The real reason? ...I wanted to see you.\\\"": "\\\"...La vraie raison ? ...Je voulais te voir.\\\"",
  "*She's smiling, but something feels forced. Like she's pushing too hard.*": "*Elle sourit, mais quelque chose semble forcé. Comme si elle en faisait trop.*",
  "\\\"...Actually, something kind of tough happened at school today.\\\"": "\\\"...En fait, un truc un peu dur s'est passé à l'école aujourd'hui.\\\"",
  "\\\"The other teachers said, 'The nurse is always so cheerful—must be nice having no worries.'\\\"": "\\\"Les autres profs ont dit : 'L'infirmière est toujours si joyeuse — ça doit être bien de ne pas avoir de soucis.'\\\"",
  "\\\"...'No worries.' Haha. That one... actually stung the most.\\\"": "\\\"...'Pas de soucis.' Haha. Celle-là... c'est celle qui a fait le plus mal.\\\"",
  "\\\"I was struggling too... but nobody asked. Not even once. Not a single 'are you okay?'\\\"": "\\\"Moi aussi j'avais du mal... mais personne n'a demandé. Pas une seule fois. Pas un seul 'ça va ?'\\\"",
  "\\\"In the nurse's office, kids come in and I smile for them, take care of them. But... who takes care of me?\\\"": "\\\"À l'infirmerie, les élèves viennent et je leur souris, je prends soin d'eux. Mais... qui prend soin de moi ?\\\"",
  "\\\"...When I go home, there's nobody. I live alone.\\\"": "\\\"...Quand je rentre chez moi, il n'y a personne. Je vis seule.\\\"",
  "\\\"So... I started staying late at school. At least in this nurse's office, I don't feel so alone.\\\"": "\\\"Alors... j'ai commencé à rester tard à l'école. Au moins dans cette infirmerie, je ne me sens pas si seule.\\\"",
  "*Her smile faded. For the first time, she's showing me her real face—without the jokes, without the teasing.*": "*Son sourire s'est effacé. Pour la première fois, elle me montre son vrai visage — sans les blagues, sans les taquineries.*",
  "*I can see the real her now. What do I say?*": "*Je peux voir la vraie elle maintenant. Que dire ?*",
  "Sit beside her and hold her": "S'asseoir à côté d'elle et la serrer dans ses bras",
  "\\\"From now on, I'll be the one to take care of you\\\"": "\\\"Désormais, c'est moi qui prendrai soin de toi\\\"",
  "\\\"......!!\\\"": "\\\"...... !!\\\"",
  "\\\"...Hey, all of a sudden... what are you...\\\"": "\\\"...Hé, tout d'un coup... qu'est-ce que tu...\\\"",
  "*She was startled at first... but soon her hands gripped my clothes tightly.*": "*Elle a d'abord été surprise... mais bientôt ses mains ont agrippé mes vêtements.*",
  "\\\"...This is weird. Have I ever wanted someone to hold me like this before?\\\"": "\\\"...C'est bizarre. Est-ce que j'ai déjà voulu que quelqu'un me serre comme ça ?\\\"",
  "\\\"...Let's just stay like this. Just a little while.\\\"": "\\\"...Restons juste comme ça. Encore un peu.\\\"",
  "\\\"...What? You'll take care of me?\\\"": "\\\"...Quoi ? Tu prendras soin de moi ?\\\"",
  "\\\"You always take care of everyone else. It's your turn to be taken care of.\\\"": "\\\"Tu prends toujours soin des autres. C'est à ton tour qu'on prenne soin de toi.\\\"",
  "\\\"...Ha. How do you always hit me right where it hurts?\\\"": "\\\"...Ha. Comment tu fais pour toujours toucher là où ça fait mal ?\\\"",
  "\\\"...Do you really mean that?\\\"": "\\\"...Tu le penses vraiment ?\\\"",

  // ===== NURSE ROUTE - Backstory =====
  "\\\"...Actually, there's a reason I became a school nurse.\\\"": "\\\"...En fait, il y a une raison pour laquelle je suis devenue infirmière scolaire.\\\"",
  "\\\"In high school, a close friend of mine got sick and was absent for a long time. The school nurse back then really took care of her.\\\"": "\\\"Au lycée, une amie proche est tombée malade et a été absente longtemps. L'infirmière scolaire de l'époque a vraiment pris soin d'elle.\\\"",
  "\\\"I wanted to be someone like that too. Someone who's there for kids when they're hurting.\\\"": "\\\"Je voulais être quelqu'un comme ça aussi. Quelqu'un qui est là pour les jeunes quand ils souffrent.\\\"",
  "\\\"But in reality... they just saw me as 'the nurse who jokes around.' Not a real teacher.\\\"": "\\\"Mais en réalité... ils me voyaient juste comme 'l'infirmière qui rigole tout le temps.' Pas une vraie enseignante.\\\"",
  "\\\"They said being serious would ruin the vibe, so... I naturally started hiding behind laughs.\\\"": "\\\"On disait qu'être sérieuse gâcherait l'ambiance, alors... j'ai naturellement commencé à me cacher derrière les rires.\\\"",
  "\\\"...I did the same with you. Approaching you with jokes and teasing. Because showing my real feelings... was terrifying.\\\"": "\\\"...J'ai fait pareil avec toi. T'approcher avec des blagues et des taquineries. Parce que montrer mes vrais sentiments... c'était terrifiant.\\\"",
  "*Her voice is trembling.*": "*Sa voix tremble.*",
  "\\\"I love the playful you and the real you—all of it\\\"": "\\\"J'aime la toi espiègle et la vraie toi — tout\\\"",
  "\\\"Thank you for showing me the real you\\\"": "\\\"Merci de me montrer la vraie toi\\\"",
  "\\\"You don't have to be scared anymore. I'm here\\\"": "\\\"Tu n'as plus besoin d'avoir peur. Je suis là\\\"",
  "\\\"...All of it?\\\"": "\\\"...Tout ?\\\"",
  "\\\"...You're the first person who's ever said that to me.\\\"": "\\\"...Tu es la première personne à m'avoir dit ça.\\\"",
  "\\\"...I don't even know how to react. This is a first.\\\"": "\\\"...Je ne sais même pas comment réagir. C'est une première.\\\"",
  "\\\"...Thankful? To me?\\\"": "\\\"...Reconnaissant ? Envers moi ?\\\"",
  "\\\"...I didn't know being honest with you could feel this comfortable.\\\"": "\\\"...Je ne savais pas qu'être honnête avec toi pouvait être aussi apaisant.\\\"",
  "\\\"...I don't have to be scared?\\\"": "\\\"...Je n'ai plus besoin d'avoir peur ?\\\"",
  "\\\"...Maybe you're the person I feel most at ease with. Funny how that works.\\\"": "\\\"...Tu es peut-être la personne avec qui je me sens le plus à l'aise. C'est drôle, non ?\\\"",

  // ===== NURSE ROUTE - Yandere Ending =====
  "I won't wear a mask in front of you anymore. Instead... I want to lock you in this infirmary forever.": "Je ne porterai plus de masque devant toi. En échange... je veux t'enfermer dans cette infirmerie pour toujours.",
  "I'll nurse you for the rest of my life... so I want you to keep being sick. So you only rely on me.": "Je te soignerai toute ma vie... alors je veux que tu restes malade. Pour que tu ne comptes que sur moi.",
  "I'm joking. ...Half joking. So if you get hurt, come straight to me. If you go anywhere else, I'll be really mad.": "Je plaisante. ...À moitié. Alors si tu te blesses, viens directement me voir. Si tu vas ailleurs, je serai vraiment en colère.",
  "*We left the infirmary and walked out of the school. The teacher linked her arm tightly with mine and wouldn't let go.*": "*Nous avons quitté l'infirmerie et sommes sortis de l'école. Elle a enlacé mon bras fermement et ne voulait pas lâcher.*",
  "...When you come to school tomorrow, drop by the infirmary first. I'll be checking attendance.": "...Quand tu viendras à l'école demain, passe d'abord par l'infirmerie. Je prendrai les présences.",
  "\\\"That wasn't uncool—that was honest.\\\"": "\\\"Ce n'était pas gênant — c'était honnête.\\\"",
  "\\\"...It's strange. Around you, I keep getting honest. That's not like me at all.\\\"": "\\\"...C'est étrange. Près de toi, je n'arrête pas d'être honnête. Ça ne me ressemble pas du tout.\\\"",
  "\\\"...When we see each other at school again, I'll act normal. But my eyes won't be able to hide it.\\\"": "\\\"...Quand on se reverra à l'école, j'agirai normalement. Mais mes yeux ne pourront pas le cacher.\\\"",
  "\\\"...So pay attention. When you walk past the nurse's office... just once.\\\"": "\\\"...Alors fais attention. Quand tu passeras devant l'infirmerie... juste un regard.\\\"",
  "*Back home. The real face she showed me in the nurse's office keeps replaying. The person who was always joking and laughing... was actually the loneliest one of all.*": "*De retour chez moi. Le vrai visage qu'elle m'a montré à l'infirmerie ne cesse de repasser. La personne qui blaguait et riait toujours... était en fait la plus solitaire de toutes.*",
  "*She's not alone anymore. I'm here. Tomorrow, I want to see her real smile.*": "*Elle n'est plus seule. Je suis là. Demain, je veux voir son vrai sourire.*",

  // ===== REGRET & REFLECT ROUTES =====
  "*...I could have said it today. Under that sunset, it was the perfect moment.*": "*...J'aurais pu le dire aujourd'hui. Sous ce coucher de soleil, c'était le moment parfait.*",
  "*It's okay. There's tomorrow. Tomorrow, I'll definitely... tell them how I feel.*": "*Ce n'est pas grave. Il y a demain. Demain, je vais... leur dire ce que je ressens, c'est sûr.*",
  "(A message came on my phone. \\\"I had fun today. Are you free tomorrow too?\\\")": "(Un message est arrivé sur mon téléphone. \\\"Je me suis bien amusé(e) aujourd'hui. Tu es libre demain aussi ?\\\")",
  "(\\\"Yeah, let's meet tomorrow.\\\" I'll definitely say it tomorrow.)": "(\\\"Oui, retrouvons-nous demain.\\\" Je le dirai demain, c'est sûr.)",
  "*And just like that, Saturday passed. Tomorrow... what should I do?*": "*Et comme ça, le samedi est passé. Demain... que devrais-je faire ?*",
  "*When I close my eyes, their face appears. I wouldn't mind falling asleep like this.*": "*Quand je ferme les yeux, leur visage apparaît. Ça ne me dérangerait pas de m'endormir comme ça.*",
  "*Saturday night deepens... Tomorrow is Sunday, the last day.*": "*La nuit de samedi s'approfondit... Demain, c'est dimanche, le dernier jour.*",
};
